### ISSUE TITLE
Update riot_pal to not send on connect

### ISSUE THREAD

**Issue by MrKevinWeiss** [RIOT-OS/RobotFW-tests#23]
It appears the attempt to flush on the interface level during connection causes some issues with the arduino.  When sending characters in bootloader mode (the first 2 seconds during startup) it could cause the arduino to stay in bootloader mode for up to 10 seconds.  The timeout is reset every time a new character is sent.  So it would be good to remove the flash on connect (or make it optional) from the riot pal interface.  If this is done then the arduino should only need a RESET_WAIT of 3 or so then everything should be good.

**Comment by smlng** [comment]
@MrKevinWeiss this should be fixed, right? Please close, if you agree.

**Comment by MrKevinWeiss** [comment]
Yup fix with CONNECT_WAIT env variable
`export CONNECT_WAIT=3`
update riot_pal and RobotFW-tests
