### ISSUE TITLE
Prepare for update to Robot Framework v4.x

### ISSUE THREAD

**Issue by ozfox** [RIOT-OS/RobotFW-tests#95]
Robot Framework 4.0 beta 1 was released on Oct 19, 2020 and the new major version has several [incompatible changes][incompatible-changes] which have to be addressed before a update can happen. The newest [release notes][rf_release_notes] contains all changes and necessary steps.

-  Changes to test and suite statuses
-  Old :FOR loop syntax is not supported anymore
-  Meaning of @{var}[item] and &{var}[item] syntax has changed
-  Argument conversion changes
-  Libdoc spec changes
-  Other backwards incompatible changes

Most important enhancements as listed in the README.

- New SKIP status
- Criticality has been removed
- Native IF/ELSE syntax
- Support for nested control structures
- Libdoc enhancements
- Argument conversion enhancements
- List and dictionary expansion with item access
- Positional-only arguments

Worth mentioning is the change from the concept of "critical tests" to a new "SKIP" status, which would need to review/rework every existing test, but in my opinion would be quite a improvement. There are several resources on the web about this feature:

- [Release Notes (4.0 beta 1): Criticality has been removed][rf_release_notes_critically_removed]
- [New `SKIP` status #3622][rf_issue_3622]
- [Remove criticality concept in favor of skip status #3624][rf_issue_3624]

[incompatible-changes]: https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-4.0b1.rst#backwards-incompatible-changes
[rf_release_notes]: https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-4.0b1.rst
[rf_release_notes_critically_removed]: https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-4.0b1.rst#criticality-has-been-removed
[rf_issue_3624]: https://github.com/robotframework/robotframework/issues/3624
[rf_issue_3622]: https://github.com/robotframework/robotframework/issues/3622

**Comment by MrKevinWeiss** [comment]
We should update the requirements.txt and the ansible script

**Comment by pokgak** [comment]
Other than test criticality, other backward-incompatible changes do not affect us. We're not using the old FOR loop syntax. @ and $ variable reference is not used to access the items directly. So we're good on that. 

> Libdoc spec changes
I'm not sure if this affects the generated output.xml that we are parsing to generate our xunit file. If so then the parsing script will need an update too.

> We should update the requirements.txt and the ansible script

We are not specifying the RF version in requirements.txt so no change is required. Not sure about the ansible script.

**Comment by MrKevinWeiss** [comment]
I think this has been done, should we close?

**Comment by ozfox** [comment]
Yes, I thought the same. Closing
